class Sequential(Module):
  __parameters__ = []
  __buffers__ = []
  training : bool
  _is_full_backward_hook : Optional[bool]
  __annotations__["0"] = __torch__.models.common.Conv
  __annotations__["1"] = __torch__.models.common.___torch_mangle_2.Conv
  __annotations__["2"] = __torch__.models.common.C3
  __annotations__["3"] = __torch__.models.common.___torch_mangle_20.Conv
  __annotations__["4"] = __torch__.models.common.___torch_mangle_45.C3
  __annotations__["5"] = __torch__.models.common.___torch_mangle_48.Conv
  __annotations__["6"] = __torch__.models.common.___torch_mangle_80.C3
  __annotations__["7"] = __torch__.models.common.___torch_mangle_83.Conv
  __annotations__["8"] = __torch__.models.common.___torch_mangle_101.C3
  __annotations__["9"] = __torch__.models.common.SPPF
  __annotations__["10"] = __torch__.models.common.___torch_mangle_110.Conv
  __annotations__["11"] = __torch__.torch.nn.modules.upsampling.Upsample
  __annotations__["12"] = __torch__.models.common.Concat
  __annotations__["13"] = __torch__.models.common.___torch_mangle_128.C3
  __annotations__["14"] = __torch__.models.common.___torch_mangle_131.Conv
  __annotations__["15"] = __torch__.torch.nn.modules.upsampling.___torch_mangle_132.Upsample
  __annotations__["16"] = __torch__.models.common.___torch_mangle_133.Concat
  __annotations__["17"] = __torch__.models.common.___torch_mangle_151.C3
  __annotations__["18"] = __torch__.models.common.___torch_mangle_154.Conv
  __annotations__["19"] = __torch__.models.common.___torch_mangle_155.Concat
  __annotations__["20"] = __torch__.models.common.___torch_mangle_173.C3
  __annotations__["21"] = __torch__.models.common.___torch_mangle_176.Conv
  __annotations__["22"] = __torch__.models.common.___torch_mangle_177.Concat
  __annotations__["23"] = __torch__.models.common.___torch_mangle_195.C3
  __annotations__["24"] = __torch__.models.yolo.Detect
